### ISSUE TITLE
Please add ISC license text inside a LICENSE file

### ISSUE THREAD

**Issue by kapouer** [NikoHadouken/node-cups#2]

**Comment by NikoHadouken** [comment]
I've added the MIT licence but it should be equivalent to ISC

**Comment by kapouer** [comment]
Well then you need to update
https://github.com/NikoHadouken/node-cups/blob/f7abefa78e604d38756be86165ee9b0eb6f0a7a4/package.json#L19

**Comment by NikoHadouken** [comment]
Here you go 👍🏼
